import assert from 'node:assert/strict';
import {pack} from 'tar-stream';
import {gzipSync} from 'node:zlib';
import {parseRepository,inspectFile,scanRepository,demoReport} from './repository-scanner.js';
assert.deepEqual(parseRepository('https://github.com/owner/repo.git'),{owner:'owner',repo:'repo'});
for(const url of ['http://github.com/a/b','https://github.com.evil.com/a/b','https://user:pass@github.com/a/b','https://github.com/a/b/tree/main','https://127.0.0.1/a/b','https://github.com/a/b?x=1'])assert.throws(()=>parseRepository(url));
const secret='ghp_'+'aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789ab';
const matches=inspectFile('config/.env.example','you@example.com\nonboarding@resend.dev\nTOKEN='+secret+'\nTOKEN='+secret,true);
assert.equal(matches.filter(f=>f.disposition==='reference').length,2);
const credentials=matches.filter(f=>f.category==='credentials');assert.equal(credentials.length,2);
assert.ok(credentials.every(f=>f.disposition==='review'));assert.deepEqual(credentials.map(f=>f.line),[3,4]);
assert.ok(!JSON.stringify(inspectFile('config.env','TOKEN='+secret)).includes(secret));
assert.equal(inspectFile('config.env','FROM=actual@company.com')[0].disposition,'review');
assert.equal(inspectFile('config.env','HOST=127.0.0.1')[0].disposition,'reference');
assert.equal(inspectFile('config.env','KEY=pk_live_1234567890abcdefghijkl')[0].disposition,'reference');
assert.equal(demoReport().findings.filter(f=>f.disposition==='review').length,1);

const sha='a'.repeat(40),tree='b'.repeat(40);
const paths=Array.from({length:70},(_,i)=>`nested/folder${i}/config.txt`);
paths.push('.github/workflows/ci.yml','vendor/config.env','build/config.env','package.lock','sample/.env.example');
const tar=pack();const chunks:Buffer[]=[];const collect=(async()=>{for await(const chunk of tar)chunks.push(chunk);})();
for(const path of paths)tar.entry({name:'root/'+path},'TOKEN='+secret);
tar.entry({name:'root/icon.png'},Buffer.from([0,137,80,78,71]));
tar.entry({name:'root/utf16.txt'},Buffer.concat([Buffer.from([255,254]),Buffer.from('TOKEN='+secret,'utf16le')]));
tar.entry({name:'root/link',type:'symlink',linkname:'/outside/secret'});
tar.finalize();await collect;const archive=gzipSync(Buffer.concat(chunks));
const urls:string[]=[];
const fetcher=(async(url:string|URL|Request)=>{
 const u=String(url);urls.push(u);
 if(u.startsWith('https://codeload.github.com/'))return new Response(archive);
 let value:unknown;
 if(u.endsWith('/a/b'))value={private:false,default_branch:'main'};
 else if(u.includes('/commits/'))value={sha,commit:{tree:{sha:tree}}};
 else value={truncated:false,tree:[...paths,'icon.png','utf16.txt','link','export-ignored.txt'].map(path=>({path,type:'blob'})).concat([{path:'submodule',type:'commit'}])};
 return new Response(JSON.stringify(value));
}) as typeof fetch;
const report=await scanRepository('https://github.com/a/b',undefined,fetcher);
assert.equal(report.scanned,paths.length+1);assert.ok(report.scanned>35);
assert.equal(report.skipped,4);assert.ok(report.partial);assert.ok(report.inventoryComplete);
assert.ok(report.coverage.some(f=>f.path==='vendor/config.env'&&f.status==='scanned'));
assert.ok(report.coverage.some(f=>f.path==='export-ignored.txt'&&f.status==='skipped'));
assert.ok(report.coverage.some(f=>f.path==='submodule'&&f.reason.includes('submodule')));
assert.ok(report.findings[0].url?.includes(sha));assert.equal(urls.length,4);
assert.ok(urls.every(u=>u.startsWith('https://api.github.com/repos/a/b')||u===`https://codeload.github.com/a/b/tar.gz/${sha}`));
assert.ok(!JSON.stringify(report).includes(secret));
const corrupt=(async(url:string|URL|Request)=>String(url).startsWith('https://codeload.github.com/')?new Response('invalid gzip'):fetcher(url)) as typeof fetch;
const interrupted=await scanRepository('https://github.com/a/b',undefined,corrupt);
assert.ok(interrupted.partial);assert.equal(interrupted.scanned,0);assert.equal(interrupted.skipped,interrupted.total);
console.log('Passed: example precision, secrets in example files, repeated lines, masking/reveal, 76 text files across all folders, UTF-16, binary/symlink/submodule/missing-file accounting, fixed hosts and corrupt archive.');
