import type { RepoReport } from './repository-scanner.js';
import { aggregateRepositoryReport, reportToText, apiKeyCandidates, type FindingGroup } from './repository-report.js';
import { repositoryRequest, repositoryProgress, nativeRepositoryEngine, type AccountState } from './auth.js';
import { repositoryExample } from './repository-example.js';
import { openInSystemBrowser } from './desktop.js';
const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;
const text = (tag:string,value:string,cls='') => {const el=document.createElement(tag);el.textContent=value;el.className=cls;return el;};
let controller:AbortController|undefined;
let reviewMode=false, configured=false;
const hostedRepository=!nativeRepositoryEngine()&&!/^http:\/\/127\.0\.0\.1:\d+$/.test(location.origin);
const bootConfig=(nativeRepositoryEngine()?Promise.resolve({available:true,designReview:false}):hostedRepository?Promise.resolve({available:false,designReview:false}):fetch('/api/repository-config').then(r=>r.json())).then(c=>{configured=c.available===true;reviewMode=c.designReview===true;if(nativeRepositoryEngine())$('preview-notice').textContent='Scans run on this computer. Subscription checks use Redaxa account services; no repository files are sent to an AI provider.';if(hostedRepository){$('scan').textContent='Open in Windows app →';$('status').textContent='Full repository checks run locally in the Redaxa Windows app.';$('preview-notice').textContent='Requires the latest Redaxa Windows app and an active Pro or Business plan. The extension opens this workspace; repository files are checked on your computer.';}if(reviewMode){$('preview-notice').textContent='Design review on this computer · live scans enabled for evaluation. Customer access requires Pro.';$('pro-access').classList.add('review-mode');}else if(!configured&&!hostedRepository){$('status').textContent='Repository checks are being prepared for release. Explore the example in the development app.';}}).catch(()=>{});
const initialRepo=new URLSearchParams(location.search).get('repo');
if(initialRepo&&initialRepo.length<=250)$<HTMLInputElement>('repo-url').value=initialRepo;
document.addEventListener('redaxa:account',event=>{const a=(event as CustomEvent<AccountState|null>).detail;if(a?.active&&['personal','pro','business'].includes(a.plan??'')){$('pro-access').classList.add('unlocked');$('pro-access').querySelector('h2')!.textContent='Your Pro workspace is ready.';}});
document.addEventListener('redaxa:need-upgrade',()=>{location.href='/dashboard.html#plans';});
const duration=(seconds:number)=>seconds<60?`${Math.max(5,Math.round(seconds/5)*5)} sec`:`${Math.ceil(seconds/60)} min`;
async function scan(demo=false){
 await bootConfig;
 if(hostedRepository){
  if(demo){$('empty').hidden=true;$('results').replaceChildren();render(repositoryExample());$('status').textContent='Illustrative example — no live scan';$('results').scrollIntoView({block:'start'});return;}
  const repository=$<HTMLInputElement>('repo-url').value.trim();
  if(!/^https:\/\/github\.com\/[A-Za-z0-9_-]+\/[A-Za-z0-9_.-]+\/?$/.test(repository)){$('status').textContent='Use the public repository home URL on https://github.com.';return;}
  try{const res=await fetch('/api/account',{cache:'no-store'});const account=await res.json();const entitled=res.ok&&account.active===true&&(typeof account.repositoryAccess==='boolean'?account.repositoryAccess:['personal','pro','business'].includes(account.plan)&&['active','trialing'].includes(account.status));
   if(!entitled){window.promptShieldAuth?.requestAccess('Sign in with Pro or Business to review repositories.');$('status').textContent='Sign in with an active Pro or Business plan to continue.';return;}
   location.href='redaxa://repository?repo='+encodeURIComponent(repository);$('status').textContent='Opening Redaxa. If nothing happens, install the latest Windows app, then try again.';
  }catch{$('status').textContent='Could not verify your subscription. Please try again.';}return;
 }
 controller?.abort();const active=new AbortController();controller=active;const scanId=crypto.randomUUID();let pollingActive=true,pollBusy=false;
 $('scan').setAttribute('disabled','');$('demo').setAttribute('disabled','');$('cancel').hidden=false;$('results').replaceChildren();$('empty').hidden=true;
 $('status').textContent=demo?'Preparing a synthetic example…':'Connecting and mapping the repository…';$('estimate').hidden=demo;$('estimate').textContent='Estimating time after the repository is mapped. Larger histories take longer.';$('progress').hidden=false;
 const started=Date.now();
 const polling=demo?undefined:setInterval(()=>{if(pollBusy)return;pollBusy=true;void repositoryProgress(scanId,active.signal).then(p=>{if(!pollingActive||!p.stage)return;$('status').textContent=`${p.stage} · ${p.checked.toLocaleString()} entries checked`;const elapsed=Math.round((Date.now()-started)/1000);$('estimate').textContent=p.estimatedRemainingSeconds?`About ${duration(p.estimatedRemainingSeconds)} remaining · ${duration(elapsed)} elapsed · estimate adjusts as new content is found`:`${duration(elapsed)} elapsed · estimating remaining time…`;}).catch(()=>{}).finally(()=>{pollBusy=false;});},1500);
 try{
  const response=await repositoryRequest({url:$<HTMLInputElement>('repo-url').value,demo},active.signal,scanId);const data=await response.json();
  if(!response.ok){if(data.code==='PRO_REQUIRED')window.promptShieldAuth?.requestAccess('Sign in to your Pro account to check repositories.');throw new Error(data.error||'Unable to start this check.');}
  render(data);$('status').textContent=data.demo?'Example complete — synthetic data':data.partial?'Review ready · some content could not be checked':'Review ready · inventory checked';$('estimate').textContent=`Completed in ${duration(data.durationMs/1000)}. Review distinct findings below.`;$('results').scrollIntoView({block:'start',behavior:'auto'});
 }catch(e){$('status').textContent=active.signal.aborted?'Scan cancelled. No report saved.':e instanceof Error?e.message:'Unable to scan.';$('empty').hidden=false;$('estimate').hidden=true;}
 finally{pollingActive=false;clearInterval(polling);$('scan').removeAttribute('disabled');$('demo').removeAttribute('disabled');$('cancel').hidden=true;$('progress').hidden=true;}
}
function render(r:RepoReport){
 const {summary:s,groups}=aggregateRepositoryReport(r);const root=$('results');
 const summary=text('section','','result-summary');summary.append(text('span',r.demo?'SYNTHETIC EXAMPLE':r.partial?'PARTIAL COVERAGE':'YOUR REPOSITORY REVIEW','eyebrow'),text('h2',s.actionable?`${s.actionable} distinct findings to review`:'No actionable matches found'));
 const apiKeys=apiKeyCandidates(groups);
 if(apiKeys.length){const alert=text('div','','api-key-alert');alert.setAttribute('role','status');alert.append(text('strong',`${apiKeys.length} potential API ${apiKeys.length===1?'key or token':'keys or tokens'} found`),text('p',`${apiKeys.filter(g=>!g.historyOnly).length} in current files · ${apiKeys.filter(g=>g.historyOnly).length} only in history. Review these first; validity has not been tested.`));summary.prepend(alert);}
 summary.append(text('p',`${r.repository} · ${r.scanned.toLocaleString()} / ${r.total.toLocaleString()} entries checked · ${r.folders} folders · ${r.skipped} not scanned`));
 const metrics=text('div','','triage-grid');for(const [label,value,cls] of [['Critical priority',s.critical,'critical'],['High priority',s.high,'high'],['Medium priority',s.medium,'medium'],['Low priority',s.low,'low']] as const){const tile=text('div','','triage-tile '+cls);tile.append(text('strong',String(value)),text('span',label));metrics.append(tile);}summary.append(metrics);
 summary.append(text('p',`${s.current} found in current files · ${s.historyOnly} found only in history · ${s.duplicatesCollapsed.toLocaleString()} repeated matches grouped`,'recap-line'));
 summary.append(text('p',`${s.reference} recognized examples or informational values are separate. Priorities describe potential impact, not confirmed vulnerabilities. No credential has been tested.`,'muted'));
 const next=text('div','','next-step');next.append(text('strong',s.critical||s.high?'Start with credentials.':'Start with context.'),text('p',s.critical||s.high?'Review the highest-priority candidates first. If a credential is real, revoke or rotate it; deleting the line alone does not remove its access.':'Check whether the remaining data is intentionally public. Informational references do not need the same response as a leaked credential.'));summary.append(next);
 const actions=text('div','','report-actions');const exportButton=text('button','Download report (.txt)','reveal-button') as HTMLButtonElement;exportButton.onclick=()=>{const url=URL.createObjectURL(new Blob([reportToText(r)],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`redaxa-${r.repository.replace(/[^a-z0-9-]/gi,'-')}-report.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};actions.append(exportButton);
 const copy=text('button','Copy report','reveal-button') as HTMLButtonElement;copy.onclick=()=>{void navigator.clipboard.writeText(reportToText(r)).then(()=>{copy.textContent='Copied — values hidden';}).catch(()=>{copy.textContent='Use Download report';});};actions.append(copy);
 const email=text('button','Draft email recap','reveal-button') as HTMLButtonElement;email.onclick=()=>{const body=`Redaxa repository review: ${r.repository}\n${s.actionable} distinct candidates: ${s.critical} critical, ${s.high} high, ${s.medium} medium, ${s.low} low priority.\n${s.current} current; ${s.historyOnly} historical only. ${s.duplicatesCollapsed} repeated matches grouped.\nCoverage: ${r.scanned}/${r.total} entries, ${r.skipped} skipped.\nThese are candidates for review, not confirmed vulnerabilities. No secret values included.\nAttach the downloaded redacted report if appropriate.`;const url=`mailto:?subject=${encodeURIComponent('Redaxa repository review')}&body=${encodeURIComponent(body)}`;void openInSystemBrowser(url).then(opened=>{if(!opened)location.href=url;}).catch(()=>{email.textContent='Copy report to your email app';});};actions.append(email);summary.append(actions,text('p','Reports always hide matched values. Email opens a draft in your email app; nothing is sent automatically.','muted'));root.append(summary);
 const sectionReveal=new Map<string,boolean>(); const reveals:{shown:boolean;set:(show:boolean)=>void;section:string}[]=[];const controls:{button:HTMLButtonElement;section?:string}[]=[];
 const update=()=>controls.forEach(c=>{const rows=reveals.filter(x=>!c.section||c.section===x.section);const shown=rows.length>0&&rows.every(x=>x.shown);c.button.textContent=shown?'Hide all':'Show all';c.button.setAttribute('aria-pressed',String(shown));});
 const control=(parent:HTMLElement,section?:string)=>{const b=text('button','Show all','reveal-button') as HTMLButtonElement;b.type='button';b.onclick=()=>{const rows=reveals.filter(x=>!section||x.section===section);const show=!rows.every(x=>x.shown);for(const key of section?[section]:['api','urgent','context','reference'])sectionReveal.set(key,show);rows.forEach(x=>x.set(show));update();};controls.push({button:b,section});parent.append(b);};
 if(groups.length){control(summary);summary.append(text('p','Values are hidden. Show only what you need to review.','muted'));}
 const row=(g:FindingGroup,section:string)=>{const card=text('article','','finding');const head=text('div','','finding-head');head.append(text('span',g.disposition==='reference'?'INFORMATIONAL':g.severity.toUpperCase()+' PRIORITY','badge '+(g.severity==='critical'||g.severity==='high'?'danger':'')),text('span',g.historyOnly?'HISTORY ONLY':'CURRENT FILES','muted'));card.append(head,text('h3',g.label),text('code',g.location?`${g.path} · ${g.location}`:`${g.path} : ${g.line}`));
 const value=text('code','•••• •••• ••••  Value hidden','masked');const bar=text('div','','value-row');const button=text('button','Show','reveal-button') as HTMLButtonElement;button.type='button';const state={shown:false,section,set:(show:boolean)=>{state.shown=show;value.textContent=show?(g.value??'Run a new scan to reveal this value.'):'•••• •••• ••••  Value hidden';button.textContent=show?'Hide':'Show';button.setAttribute('aria-pressed',String(show));button.setAttribute('aria-label',`${show?'Hide':'Show'} ${g.label}`);}};button.onclick=()=>{state.set(!state.shown);update();};reveals.push(state);state.set(sectionReveal.get(section)??false);bar.append(value,button);card.append(bar,text('p',g.reason),text('p',g.action));
 if(g.url&&/^https:\/\/github\.com\//.test(g.url)){const a=text('a','Open current file on GitHub ↗') as HTMLAnchorElement;a.href=g.url;a.target='_blank';a.rel='noopener noreferrer';card.append(a);}
 const locations=text('details','','occurrences');locations.append(text('summary',`${g.occurrenceCount} occurrence${g.occurrenceCount===1?'':'s'} · ${g.currentCount} current / ${g.historyCount} historical`));for(const o of g.occurrences){locations.append(text('code',`${o.path}${o.location?' · '+o.location:' : '+o.line}`));}card.append(locations);return card;};
 const sections:[string,string,FindingGroup[]][]=[['api','API keys & tokens — review first',apiKeys],['urgent','Other high-priority findings',groups.filter(g=>g.disposition==='review'&&g.kind!=='secret'&&['critical','high'].includes(g.severity))],['context','Needs context',groups.filter(g=>g.disposition==='review'&&g.kind!=='secret'&&!['critical','high'].includes(g.severity))],['reference','Examples & informational references',groups.filter(g=>g.disposition==='reference')]];
 for(const [key,label,items] of sections){if(!items.length)continue;const section=text(key==='reference'?'details':'section','','finding-section '+(key==='reference'?'reference-group':''));if(key==='reference')section.append(text('summary',`${label} (${items.length})`));const heading=text('div','','finding-head section-heading');heading.append(text('h3',`${label} · ${items.length}`));control(heading,key);section.append(heading);const listing=text('div','');section.append(listing);let count=0;const more=text('button','Show more findings','reveal-button') as HTMLButtonElement;const append=()=>{for(const g of items.slice(count,count+12))listing.append(row(g,key));count+=12;more.hidden=count>=items.length;more.textContent=`Show more findings (${Math.max(0,items.length-count)} remaining)`;update();};append();more.onclick=append;section.append(more);root.append(section);}
 const coverage=text('details','','coverage-list');coverage.append(text('summary',`Coverage & limitations · ${r.total.toLocaleString()} entries`));coverage.append(text('p',r.inventoryComplete?'Accessible inventory reconciled.':'Inventory incomplete: totals may be a lower bound.'));r.warnings.forEach(w=>coverage.append(text('p',w)));for(const f of [...r.coverage].sort((a,b)=>Number(a.status==='scanned')-Number(b.status==='scanned'))){const el=text('div','','coverage-row');el.append(text('code',f.path),text('span',`${f.status==='scanned'?'Checked':'Not scanned'} — ${f.reason}`));coverage.append(el);}root.append(coverage);
}
$('repo-form').addEventListener('submit',e=>{e.preventDefault();void scan();});$('demo').addEventListener('click',()=>void scan(true));$('cancel').addEventListener('click',()=>controller?.abort());
