import assert from 'node:assert/strict';
import {pack} from 'tar-stream';
import {gzipSync} from 'node:zlib';
import {parseRepository,inspectFile,scanRepository,demoReport} from './repository-scanner.js';
assert.deepEqual(parseRepository('https://github.com/owner/repo.git'),{owner:'owner',repo:'repo'});
for(const url of ['http://github.com/a/b','https://github.com.evil.com/a/b','https://user:pass@github.com/a/b','https://github.com/a/b/tree/main','https://127.0.0.1/a/b','https://github.com/a/b?x=1'])assert.throws(()=>parseRepository(url));
const secret='ghp_'+'aBcDeFgHiJkLmNoPqRsTuVwXyZ0123456789ab';
const matches=inspectFile('config/.env.example','you@example.com\nonboarding@resend.dev\nTOKEN='+secret+'\nTOKEN='+secret,true);
assert.equal(matches.filter(f=>f.disposition==='reference').length,2);
const credentials=matches.filter(f=>f.category==='credentials');assert.equal(credentials.length,2);
assert.ok(credentials.every(f=>f.disposition==='review'));assert.deepEqual(credentials.map(f=>f.line),[3,4]);
assert.ok(!JSON.stringify(inspectFile('config.env','TOKEN='+secret)).includes(secret));
assert.equal(inspectFile('config.env','FROM=actual@company.com')[0].disposition,'review');
assert.equal(inspectFile('config.env','HOST=127.0.0.1')[0].disposition,'reference');
assert.equal(inspectFile('config.env','KEY=pk_live_1234567890abcdefghijkl')[0].disposition,'reference');
assert.equal(demoReport().findings.filter(f=>f.disposition==='review').length,1);

const sha='a'.repeat(40),tree='b'.repeat(40);
const paths=Array.from({length:70},(_,i)=>`nested/folder${i}/config.txt`);
paths.push('.github/workflows/ci.yml','vendor/config.env','build/config.env','package.lock','sample/.env.example');
const tar=pack();const chunks:Buffer[]=[];const collect=(async()=>{for await(const chunk of tar)chunks.push(chunk);})();
for(const path of paths)tar.entry({name:'root/'+path},'TOKEN='+secret);
tar.entry({name:'root/icon.png'},Buffer.from([0,137,80,78,71]));
tar.entry({name:'root/utf16.txt'},Buffer.concat([Buffer.from([255,254]),Buffer.from('TOKEN='+secret,'utf16le')]));
tar.entry({name:'root/link',type:'symlink',linkname:'/outside/secret'});
tar.finalize();await collect;const archive=gzipSync(Buffer.concat(chunks));
const urls:string[]=[];
const fetcher=(async(url:string|URL|Request)=>{
 const u=String(url);urls.push(u);
 if(u.startsWith('https://codeload.github.com/'))return new Response(archive);
 let value:unknown;
 if(u.endsWith('/a/b'))value={private:false,default_branch:'main'};
 else if(u.includes('/commits/'))value={sha,commit:{tree:{sha:tree}}};
 else value={truncated:false,tree:[...paths,'icon.png','utf16.txt','link','export-ignored.txt'].map(path=>({path,type:'blob'})).concat([{path:'submodule',type:'commit'}])};
 return new Response(JSON.stringify(value));
}) as typeof fetch;
const report=await scanRepository('https://github.com/a/b',undefined,fetcher);
assert.equal(report.scanned,paths.length+1);assert.ok(report.scanned>35);
assert.equal(report.skipped,4);assert.ok(report.partial);assert.ok(report.inventoryComplete);
assert.ok(report.coverage.some(f=>f.path==='vendor/config.env'&&f.status==='scanned'));
assert.ok(report.coverage.some(f=>f.path==='export-ignored.txt'&&f.status==='skipped'));
assert.ok(report.coverage.some(f=>f.path==='submodule'&&f.reason.includes('submodule')));
assert.ok(report.findings[0].url?.includes(sha));assert.equal(urls.length,4);
assert.ok(urls.every(u=>u.startsWith('https://api.github.com/repos/a/b')||u===`https://codeload.github.com/a/b/tar.gz/${sha}`));
assert.ok(!JSON.stringify(report).includes(secret));
const corrupt=(async(url:string|URL|Request)=>String(url).startsWith('https://codeload.github.com/')?new Response('invalid gzip'):fetcher(url)) as typeof fetch;
const interrupted=await scanRepository('https://github.com/a/b',undefined,corrupt);
assert.ok(interrupted.partial);assert.equal(interrupted.scanned,0);assert.equal(interrupted.skipped,interrupted.total);
console.log('Passed: example precision, secrets in example files, repeated lines, masking/reveal, 76 text files across all folders, UTF-16, binary/symlink/submodule/missing-file accounting, fixed hosts and corrupt archive.');
// Precision: published demo keys, lockfile names, documentation placeholders.
const supabaseDemo='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU';
const demo=inspectFile('.env.local','SUPABASE_SERVICE_ROLE_KEY='+supabaseDemo).find(f=>f.kind==='secret');
assert.equal(demo?.label,'JWT · public Supabase demo key');assert.equal(demo?.severity,'low');
const forged=supabaseDemo.slice(0,-4)+'AAAA';
assert.equal(inspectFile('.env','KEY='+forged).find(f=>f.kind==='secret')?.severity,'critical','a demo issuer claim without the demo signature stays privileged');
assert.ok(inspectFile('pnpm-lock.yaml','  passwd: 1.0.0\n').every(f=>f.disposition==='reference'));
assert.ok(inspectFile('src/types.ts',"const o = { secret: '<SECRET>' }").filter(f=>f.category==='credentials').every(f=>f.disposition==='reference'));
assert.equal(inspectFile('src/client.ts',"   * password: 'hunter2-x9Q'").find(f=>f.category==='credentials')?.severity,'low');
assert.ok(inspectFile('src/api.ts',"// email: 'example@email.com'").filter(f=>f.kind==='email').every(f=>f.disposition==='reference'));
assert.equal(inspectFile('tests/fixtures/users.ts',"email: 'maria.bianchi@gmail.com'").find(f=>f.kind==='email')?.severity,'low');
console.log('Passed precision: Supabase demo keys (signature-checked), lockfile names, documentation placeholders and sample data.');
// Archive-only mode (web): no GitHub API call, commit read from the archive root, lockfiles audited.
const headSha='c'.repeat(40);
const headTar=pack();const headChunks:Buffer[]=[];const headCollect=(async()=>{for await(const chunk of headTar)headChunks.push(chunk);})();
headTar.entry({name:`b-${headSha}/config.env`},'TOKEN='+secret);
headTar.entry({name:`b-${headSha}/package-lock.json`},JSON.stringify({lockfileVersion:3,packages:{'':{},'node_modules/minimist':{version:'1.2.0'}}}));
headTar.finalize();await headCollect;const headArchive=gzipSync(Buffer.concat(headChunks));
const archiveUrls:string[]=[];
const archiveFetcher=(async(url:string|URL|Request)=>{const u=String(url);archiveUrls.push(u);
  if(u==='https://codeload.github.com/a/b/tar.gz/HEAD')return new Response(headArchive);
  if(u==='https://api.osv.dev/v1/querybatch')return Response.json({results:[{vulns:[]}]});
  return new Response('unexpected',{status:500});}) as typeof fetch;
const archiveOnly=await scanRepository('https://github.com/a/b',undefined,archiveFetcher,false,{archiveOnly:true});
assert.ok(!archiveUrls.some(u=>u.startsWith('https://api.github.com/')),'archive-only never calls the GitHub API');
assert.equal(archiveOnly.commit,headSha);
assert.ok(archiveOnly.findings.some(f=>f.url?.includes(`/blob/${headSha}/config.env`)));
assert.equal(archiveOnly.dependencies?.checked,1);
const missing=(async()=>new Response('',{status:404})) as typeof fetch;
await assert.rejects(scanRepository('https://github.com/a/private',undefined,missing,false,{archiveOnly:true}),/Only public GitHub repositories/);
// Files with many matches: line numbers come from a newline index, and a capped
// caller keeps credentials ahead of personal data. Both used to be quadratic.
{
  const started=performance.now();
  const emails=inspectFile('data/users.csv','a@b.cc\n'.repeat(60_000));
  assert.equal(emails.length,60_000);assert.equal(emails.at(-1)?.line,60_000);
  assert.ok(performance.now()-started<20_000,'line numbers must not rescan the file for every match');
  const key='ghp_'+'k'.repeat(36);
  const capped=inspectFile('data/mixed.env','a@b.cc\n'.repeat(20_000)+'TOKEN='+key+'\n',false,false,5);
  assert.equal(capped.length,5);assert.equal(capped[0].kind,'secret');assert.equal(capped[0].line,20_001);
  const minified=inspectFile('dist/app.min.js','x="a@b.cc";'.repeat(40_000));
  assert.equal(minified.length,40_000);assert.ok(minified.every(f=>f.line===1));
}
console.log('Archive-only scan: no API calls, commit from archive root, lockfile audit and private/missing repositories passed.');
