// Generated by scripts/build-extension-engine.mjs from the TypeScript sources. Do not edit.
// The policy layer: given what detection FOUND, decide what SHOULD HAPPEN.
//
// This is deliberately a separate module from scanner.ts — the core
// architectural boundary of the product:
//
//   Detection:   "What is here?"        (scanner.ts)
//   Policy:      "What should happen?"  (this file)
//   Enforcement: "Make it happen."      (each surface: web/extension/desktop)
//   Audit:       "What happened?"       (scan events, metadata only)
//
// Rules are deterministic, ordered, and explainable: every decision names the
// rule that produced it and the findings that matched, so any surface can
// answer "why?" without re-deriving the logic. No rule here ever inspects the
// raw text — policies speak only the detection vocabulary (category/kind/
// severity), which is what will later let organizations author their own
// rules without touching regexes.
const actionStrength = { allow: 0, warn: 1, redact: 2, block: 3 };
const severityRank = { low: 0, medium: 1, high: 2, critical: 3 };
function findingMatches(finding, rule) {
    if (rule.match.categories && !rule.match.categories.includes(finding.category))
        return false;
    if (rule.match.kinds && !rule.match.kinds.includes(finding.kind))
        return false;
    if (rule.match.minSeverity && severityRank[finding.severity] < severityRank[rule.match.minSeverity])
        return false;
    return true;
}
export function evaluatePolicy(findings, rules) {
    const matched = [];
    for (const rule of rules) {
        if (!rule.enabled)
            continue;
        // A rule with no conditions would silently match every prompt; that is
        // never an intentional policy, so it is ignored rather than honored.
        if (!rule.match.categories && !rule.match.kinds && !rule.match.minSeverity)
            continue;
        const indexes = findings.map((finding, index) => (findingMatches(finding, rule) ? index : -1)).filter((index) => index >= 0);
        if (indexes.length === 0)
            continue;
        matched.push({ ruleId: rule.id, ruleName: rule.name, action: rule.action, reason: rule.reason, findingIndexes: indexes });
    }
    if (matched.length === 0)
        return { action: "allow", decidedBy: null, matched };
    const decidedBy = matched.reduce((strongest, candidate) => (actionStrength[candidate.action] > actionStrength[strongest.action] ? candidate : strongest));
    return { action: decidedBy.action, decidedBy, matched };
}
export function buildOrganizationPolicy(overrides) {
    const orgReasons = {
        credentials: "Your organization's policy covers passwords, API keys and private keys.",
        financial: "Your organization's policy covers financial data like cards and IBANs.",
        personal: "Your organization's policy covers personal identifiers.",
        custom: "Your organization's policy covers its protected terms."
    };
    return defaultPersonalPolicy.map((rule) => {
        const category = rule.match.categories?.[0];
        const override = category ? overrides[category] : undefined;
        if (!override || !category)
            return rule;
        return {
            ...rule,
            id: `org-${category}`,
            name: `Organization: ${rule.name}`,
            action: override.action,
            match: override.minSeverity ? { ...rule.match, minSeverity: override.minSeverity } : rule.match,
            reason: orgReasons[category]
        };
    });
}
export const defaultPersonalPolicy = [
    {
        id: "default-credentials",
        name: "Protect credentials",
        enabled: true,
        match: { categories: ["credentials"] },
        action: "redact",
        reason: "Passwords, API keys and private keys should never reach an AI model."
    },
    {
        id: "default-financial",
        name: "Protect financial data",
        enabled: true,
        match: { categories: ["financial"] },
        action: "redact",
        reason: "Card numbers, IBANs and wallet addresses are directly abusable if leaked."
    },
    {
        id: "default-personal",
        name: "Flag personal data",
        enabled: true,
        match: { categories: ["personal"] },
        action: "warn",
        reason: "Personal identifiers were found — review before sharing."
    },
    {
        id: "default-custom-terms",
        name: "Flag protected terms",
        enabled: true,
        match: { categories: ["custom"] },
        action: "warn",
        reason: "A term you marked as protected appears in this prompt."
    }
];
